name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.KID }}
          aws-secret-access-key: ${{ secrets.SAC }}
          aws-region: us-east-1

      - name: List files in the repository
        run: ls -la

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://az-testbucket-virginia --exclude "*" --include "index.html" --include "error.html" --acl public-read
          aws s3 website s3://az-testbucket-virginia --index-document index.html --error-document error.html


### Workflow syntax for GitHub Actions
### https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions